<a href="https://colab.research.google.com/github/mohammedaslanshas/codomax-ds-internship/blob/main/Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df = df.drop(columns=["Cabin"])
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df = df.drop_duplicates()
df = df.reset_index(drop=True)
df = df[["Name", "Age", "Sex", "Pclass", "Survived", "Fare", "Embarked"]]
df = df.rename(columns={"Sex": "Gender", "Pclass": "Ticketclass"})
df["Ticketclass"] = df["Ticketclass"].astype("category")
df["Survived"] = df["Survived"].astype(bool)

print(df.info())   # verify it matches Day 7's final state

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         891 non-null    object
 1   Age          891 non-null    float64
 2   Gender       891 non-null    object
 3   Ticketclass  891 non-null    category
 4   Survived     891 non-null    bool
 5   Fare         891 non-null    float64
 6   Embarked     891 non-null    object
dtypes: bool(1), category(1), float64(2), object(3)
memory usage: 36.8+ KB
None

In [2]:
df.groupby("Gender")["Survived"].mean()

Gender  Ticketclass
female  1              0.968085
        2              0.921053
        3              0.500000
male    1              0.368852
        2              0.157407
        3              0.135447
Name: Survived, dtype: float64

In [3]:
df.groupby("Gender")["Age"].agg(["mean","min","max","count"])

             mean   min   max  count
Gender
female  27.929936  0.75  63.0    314
male    30.140676  0.42  80.0    577

In [4]:
df.groupby(["Gender","Ticketclass"], observed=True)["Survived"].mean()

Gender  Ticketclass
female  1              0.968085
        2              0.921053
        3              0.500000
male    1              0.368852
        2              0.157407
        3              0.135447
Name: Survived, dtype: float64

In [5]:
df["Fare"].sum()

np.float64(28693.9493)

In [6]:
df["Fare"].mean()

np.float64(32.204207968574636)

In [7]:
df["Fare"].median()

14.4542

In [8]:
df["Fare"].std()

49.693428597180905

In [9]:
df["Fare"].count()

np.int64(891)

In [10]:
df["Age"].value_counts()

Age
28.00    202
24.00     30
22.00     27
18.00     26
30.00     25
        ...
24.50      1
0.67       1
0.42       1
34.50      1
74.00      1
Name: count, Length: 88, dtype: int64

In [11]:
df.corr(numeric_only=True)

               Age  Survived      Fare
Age       1.000000 -0.064910  0.096688
Survived -0.064910  1.000000  0.257307
Fare      0.096688  0.257307  1.000000

In [12]:
df.corr(numeric_only=True)["Survived"].sort_values(ascending=False)

Survived    1.000000
Fare        0.257307
Age        -0.064910
Name: Survived, dtype: float64

In [13]:
pd.pivot_table(df,values="Survived", index = "Gender", columns="Ticketclass" , aggfunc ="mean")

/tmp/ipykernel_34842/2536358632.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(df,values="Survived", index = "Gender", columns="Ticketclass" , aggfunc ="mean")

Ticketclass         1         2         3
Gender
female       0.968085  0.921053  0.500000
male         0.368852  0.157407  0.135447

In [14]:
df.groupby("Ticketclass")["Survived"].mean()

/tmp/ipykernel_34842/3886598681.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Ticketclass")["Survived"].mean()

Ticketclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [15]:
df.groupby("Gender")["Survived"].mean()

Gender
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [16]:
df.corr(numeric_only=True)["Survived"]

Age        -0.064910
Survived    1.000000
Fare        0.257307
Name: Survived, dtype: float64

In [17]:
df.groupby("Ticketclass")["Fare"].mean()

/tmp/ipykernel_34842/2502428670.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Ticketclass")["Fare"].mean()

Ticketclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [18]:
#1.Gives the survival rate by gender
df.groupby("Gender")["Survived"].mean()

Gender
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [19]:
#2.Gives the survival rate by Ticketclass
df.groupby("Ticketclass")["Survived"].mean()

/tmp/ipykernel_34842/3753080928.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Ticketclass")["Survived"].mean()

Ticketclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [20]:
#3.Builded an pivot table which gives survival rate inorder to gender and ticketclass
pd.pivot_table(df, values="Survived",index="Gender",columns="Ticketclass",aggfunc="mean")

/tmp/ipykernel_34842/1031525552.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(df, values="Survived",index="Gender",columns="Ticketclass",aggfunc="mean")

Ticketclass         1         2         3
Gender
female       0.968085  0.921053  0.500000
male         0.368852  0.157407  0.135447

In [21]:
#4.Correlation matrix for survival rate which gives age a -1 correlation,Survived a +1 correlation and for Fare a 0 correlation which all three represent the relationship among to the Survived
df.corr(numeric_only=True)["Survived"].sort_values(ascending=False)

Survived    1.000000
Fare        0.257307
Age        -0.064910
Name: Survived, dtype: float64